<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="com.taxilla.apps.testscripts.TC_000_Cancellation_OutwardTransactionV3">
        <methods>
          <include name="cancellationOfRequestInOutwardTransactionV3"/>
          <include name="init"/>
          <include name="initial"/>
        </methods>
      </class> <!-- com.taxilla.apps.testscripts.TC_000_Cancellation_OutwardTransactionV3 -->
      <class name="com.taxilla.apps.testscripts.TC_006_ValidationCheckForError1_OutwardTransactionV3App">
        <methods>
          <include name="init"/>
          <include name="verifyErrorPhase1InOutwardTransactionV3"/>
          <include name="initial"/>
        </methods>
      </class> <!-- com.taxilla.apps.testscripts.TC_006_ValidationCheckForError1_OutwardTransactionV3App -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
